os:
  # opens current buffer if using edit command with lazygit.nvim
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "<cmd>q | silent! e {{filename}}<CR>")'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "<cmd>q | silent! e {{filename}} | {{line}}<CR>")'
  editPreset: "nvim-remote" # handles neovim better (ie. edits without printing command output)
gui:
  statusPanelView: allBranchesLog
  switchTabsWithPanelJumpKeys: true
  showRootItemInFileTree: false
  useHunkModeInStagingView: false
  showNumstatInFilesView: false

  commitHashLength: 5
  scrollHeight: 4

  authorColors:
    "gabrielrov": "blue"
keybinding:
  universal:
    quit: <Esc>
    return: <c-k>

    confirm: <c-j>
    goInto: <c-j>
    submitEditorText: <c-j>
    confirmMenu: <c-j>
    confirmSuggestion: <c-j>
    confirmInEditor: <c-j>

    startSearch: <c-n>

    confirmInEditor-alt: <disabled>
    scrollUpMain-alt1: <disabled>
    scrollDownMain-alt1: <disabled>
  status:
    recentRepos: <c-j>
  commits:
    moveDownCommit: J
    moveUpCommit: K
notARepository: skip
promptToReturnFromSubprocess: false
git:
  autoFetch: false
