os:
  # opens current buffer if using edit command with lazygit.nvim
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "<cmd>q | silent! e {{filename}}<CR>")'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "<cmd>q | silent! e {{filename}} | {{line}}<CR>")'
  editPreset: "nvim-remote" # handles neovim better (e.g. edits without printing command output)
gui:
  statusPanelView: allBranchesLog
  switchTabsWithPanelJumpKeys: true
  showRootItemInFileTree: false
  useHunkModeInStagingView: false
  showNumstatInFilesView: false

  commitHashLength: 5
  scrollHeight: 4

  skipSwitchWorktreeOnCheckoutWarning: true
  authorColors:
    "gabrielrov": "blue"
keybinding:
  universal:
    quit: [<esc>, <c-c>]
    return: <c-k>

    confirm: [<c-j>, <enter>]
    goInto: [<c-j>, <enter>]
    submitEditorText: [<c-j>, <enter>]
    confirmMenu: [<c-j>, <enter>]
    confirmSuggestion: [<c-j>, <enter>]
    confirmInEditor: <c-j>

    startSearch: [<c-n>, /]

    scrollUpMain: [<ctrl+u>, <pgup>]
    scrollDownMain: [<ctrl+d>, <pgdown>]
  status:
    recentRepos: [<c-j>, <enter>]
  commits:
    moveDownCommit: J
    moveUpCommit: K
notARepository: skip
promptToReturnFromSubprocess: false
git:
  autoFetch: false
